apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deploy
  labels:
    app: healthservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthservice
  template:
    metadata:
      labels:
        app: healthservice
    spec:
      containers:
      - name: healthservice-container
        image: alekhya83/healthservice
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthservice-np-service
  labels:
    app: healthservice
spec:
  selector:
    app: healthservice

  type: NodePort
  ports:
  - nodePort: 31231
    port: 8082
    targetPort: 8082
