apiVersion: apps/v1
kind: Deployment
metadata:
  name: alekhya-deploy
  labels:
    app: healthcare
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare-container
        image: alekhya83/healthcare
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-np-service
  labels:
    app: healthcare
spec:
  selector:
    app: healthcare

  type: NodePort
  ports:
  - nodePort: 31231
    port: 8082
    targetPort: 8082
